#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                           
# 

general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(0, 0, 0)
}

input-field {
    monitor = DP-5
    size = 250, 40
    outline_thickness = 2
    rounding = -1 # full pill
    outer_color = rgb(255, 255, 255) # white outline
    inner_color = rgba(0, 0, 0, 0) # keep the inside black
    font_color = rgb(255, 255, 255) # dots
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.3 # Scale of dots' absolute size, 0.0 - 1.0
    placeholder_text = # Text rendered in the input box when it's empty.
    fail_color = rgb(255, 80, 80) # if authentication failed, changes outer_color and fail message color
    position = 0, 0
    halign = center
    valign = center
}
