all:
  children:
    bees:
      hosts:
        b0:
          ansible_host: 10.0.1.150
          become: yes
        b1:
          ansible_host: 10.0.1.151
          become: yes
        b2:
          ansible_host: 10.0.1.152
          become: yes

    rockets:
      hosts:
        rocketpack-2:
          ansible_host: 10.147.20.214
          ansible_user: lucid
          become: yes
        rocketpack-3:
          ansible_host: 10.147.20.157
          ansible_user: lucid
          become: yes
    outernet:
      children:
        prod:
          hosts:
            prod1:
              ansible_host: 172.26.1.11
              ansible_user: administrator
            prod2:
              ansible_host: 172.26.1.12
              ansible_user: administrator
        test:
          hosts:
            test-rig:
              ansible_host: 172.26.1.1
              ansible_user: administrator
